[project]
name = "pokemon-vortex-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
